export const PRICING_PLANS = [
  {
    id: 'free',
    name: 'Free',
    badge: 'Free Forever',
    price: 0,
    priceDisplay: '$0',
    period: 'forever',
    tagline: 'Start tracking in 5 minutes. No credit card needed.',
    highlighted: false,
    cta: 'Get Started Free',
    ctaNote: 'No credit card required',
    ctaHref: '/dashboard/signup',
    features: [
      { text: '500 events per month', included: true },
      { text: 'Meta CAPI only', included: true },
      { text: '1 pixel', included: true },
      { text: 'Basic dashboard and overview', included: true },
      { text: 'Event logs — last 24 hours', included: true },
      { text: 'Website scanner — 3 scans/month', included: true },
      { text: 'Playground — 5 test events/day', included: true },
      { text: 'TikTok, GA4 and Google Ads', included: false },
      { text: 'Lead Manager', included: false },
      { text: 'Live Stream and Event Replay', included: false },
      { text: 'Advanced tools', included: false },
      { text: 'Email alerts', included: false },
    ]
  },
  {
    id: 'pro',
    name: 'Pro',
    badge: 'Most Popular',
    price: 15,
    priceDisplay: '$15',
    period: 'per month',
    tagline: 'Everything you need to scale your ad performance.',
    highlighted: true,
    cta: 'Get Pro — $15/mo',
    ctaNote: 'Start with 7-day free trial (no credit card). Cancel anytime.',
    ctaHref: '/billing',
    features: [
      { text: '25,000 events per month', included: true },
      { text: 'Meta, TikTok, GA4 and Google Ads', included: true },
      { text: '3 pixels', included: true },
      { text: 'Lead Manager with scoring and feedback loop', included: true },
      { text: 'Live Stream and Event Replay', included: true },
      { text: 'Raw Data access', included: true },
      { text: 'Cookie Lifetime Extender — 180 days', included: true },
      { text: 'Reverse Proxy — bypass ad blockers', included: true },
      { text: 'HTTP Headers Management', included: true },
      { text: 'Anomaly Detection and email alerts', included: true },
      { text: 'All tools unlocked', included: true },
      { text: 'Priority support', included: true },
      { text: '5 team members', included: false },
    ]
  },
  {
    id: 'agency',
    name: 'Agency',
    badge: 'For Agencies',
    price: 45,
    priceDisplay: '$45',
    period: 'per month',
    tagline: 'Manage multiple clients under one powerful dashboard.',
    highlighted: false,
    cta: 'Get Agency — $45/mo',
    ctaNote: 'Start with 7-day free trial (no credit card). Trusted by agencies.',
    ctaHref: '/billing',
    features: [
      { text: 'Unlimited events', included: true },
      { text: 'Meta, TikTok, GA4 and Google Ads', included: true },
      { text: '25 pixels across all clients', included: true },
      { text: 'Everything in Pro', included: true },
      { text: '5 team members with permissions', included: true },
      { text: 'Client data fully isolated', included: true },
      { text: 'All GTM templates including premium', included: true },
      { text: 'Early access to new features', included: true },
      { text: 'Dedicated support', included: true },
    ]
  }
]
